ALTER TABLE "Project"
ADD COLUMN IF NOT EXISTS "description" TEXT NOT NULL DEFAULT '';

ALTER TABLE "Project"
ADD COLUMN IF NOT EXISTS "liveUrl" TEXT;

ALTER TABLE "Project"
ADD COLUMN IF NOT EXISTS "githubUrl" TEXT;

ALTER TABLE "Project"
ALTER COLUMN "thumbnail" DROP NOT NULL;
