services:
  - type: web
    name: jontro-backend
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
